/**
 * An enumeration of known ID3 picture types.
 */
export enum ID3PictureType {
  OTHER = 0,
  FILE_ICON_32_X_32 = 1,
  FILE_ICON_OTHER = 2,
  COVER_FRONT = 3,
  COVER_BACK = 4,
  LEAFLET_PAGE = 5,
  MEDIA_LABEL = 6,
  LEAD_ARTIST = 7,
  ARTIST = 8,
  CONDUCTOR = 9,
  GROUP = 10,
  COMPOSER = 11,
  LYRICIST = 12,
  LOCATION = 13,
  RECORDING = 14,
  PERFORMANCE = 15,
  SCREEN_CAPTURE = 16,
  BRIGHT_FISH = 17,
  ILLUSTRATION = 18,
  BAND_LOGO = 19,
  STUDIO_LOGO = 20,
}
